<?php

namespace frontend\modules\myuser;
use yii\base\Module;

class MyUser extends Module
{
    public $controllerNamespace = 'frontend\modules\user\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}